services:
  master1:
    build: .
    hostname: master1
    container_name: master1
    ports:
      - "9871:9870" # NameNode HTTP
      - "8088:8088" # YARN ResourceManager
    volumes:
      - master1-journalnode:/home/hadoop/hadoopdata/hdfs/journalnode
      - master1-namenode:/home/hadoop/hadoopdata/hdfs/namenode
      - master1-zookeeper:/home/hadoop/zookeeper/data
    environment:
      - MYID=1
      - ROLE=master
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'QuorumPeerMain|NameNode|DFSZKFailoverController|ResourceManager|JournalNode'"]
      interval: 30s
      timeout: 10s
      retries: 5
    mem_limit: 2g
    cpus: 1.0

  master2:
    build: .
    hostname: master2
    container_name: master2
    ports:
      - "9872:9870" # NameNode HTTP
      - "8089:8088" # YARN ResourceManager
    volumes:
      - master2-journalnode:/home/hadoop/hadoopdata/hdfs/journalnode
      - master2-namenode:/home/hadoop/hadoopdata/hdfs/namenode
      - master2-zookeeper:/home/hadoop/zookeeper/data
    environment:
      - MYID=2
      - ROLE=master
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'QuorumPeerMain|NameNode|DFSZKFailoverController|ResourceManager|JournalNode'"]
      interval: 30s
      timeout: 10s
      retries: 5
    mem_limit: 1.5g
    cpus: 1.0

  master3:
    build: .
    hostname: master3
    container_name: master3
    ports:
      - "9873:9870" # NameNode HTTP
      - "8090:8088" # YARN ResourceManager
    volumes:
      - master3-journalnode:/home/hadoop/hadoopdata/hdfs/journalnode
      - master3-namenode:/home/hadoop/hadoopdata/hdfs/namenode
      - master3-zookeeper:/home/hadoop/zookeeper/data
    environment:
      - MYID=3
      - ROLE=master
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'QuorumPeerMain|NameNode|DFSZKFailoverController|ResourceManager|JournalNode'"]
      interval: 30s
      timeout: 10s
      retries: 5
    mem_limit: 1.5g
    cpus: 0.75

  worker1:
    build: .
    hostname: worker1
    container_name: worker1
    volumes:
      - worker1-datanode:/home/hadoop/hadoopdata/hdfs/datanode
    environment:
      - ROLE=worker
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'DataNode|NodeManager'"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    mem_limit: 2g
    cpus: 1.0
volumes:
  master1-journalnode:
  master1-namenode:
  master1-zookeeper:
  master2-journalnode:
  master2-namenode:
  master2-zookeeper:
  master3-journalnode:
  master3-namenode:
  master3-zookeeper:
  worker1-datanode: