version: '3'

services:
  master1:
    build: .
    hostname: master1
    container_name: master1
    ports:
      - "9871:9870"  # NameNode HTTP
      - "8021:8020"  # NameNode
      - "2181:2181"  # Zookeeper
      - "2888:2888"  # Zookeeper peer
      - "3888:3888"  # Zookeeper leader election
      - "8088:8088"  # YARN ResourceManager
    volumes:
      - ./config/core-site.xml:/home/hadoop/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/home/hadoop/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/mapred-site.xml:/home/hadoop/hadoop/etc/hadoop/mapred-site.xml
      - ./config/yarn-site.xml:/home/hadoop/hadoop/etc/hadoop/yarn-site.xml
      - ./config/hadoop-env.sh:/home/hadoop/hadoop/etc/hadoop/hadoop-env.sh
      - ./config/zoo.cfg:/home/hadoop/zookeeper/conf/zoo.cfg
      - master1-journalnode:/home/hadoop/hadoopdata/hdfs/journalnode
      - master1-namenode:/home/hadoop/hadoopdata/hdfs/namenode
      - master1-zookeeper:/home/hadoop/zookeeper/data
    environment:
      - MYID=1
    command: >
      bash -c "
      echo $$MYID > /home/hadoop/zookeeper/data/myid &&
      sudo service ssh start &&
      /home/hadoop/zookeeper/bin/zkServer.sh start &&
      hdfs --daemon start journalnode &&
      sleep 5 &&
      if [ $$MYID -eq 1 ]; then
        hdfs namenode -format mycluster &&
        hdfs --daemon start namenode &&
        hdfs zkfc -formatZK;
      else
        hdfs namenode -bootstrapStandby &&
        hdfs --daemon start namenode &&
        hdfs --daemon start zkfc;
      fi &&
      yarn --daemon start resourcemanager &&
      tail -f /dev/null"

  master2:
    build: .
    hostname: master2
    container_name: master2
    ports:
      - "9872:9870"
      - "8022:8020"
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"
      - "8089:8088"
    volumes:
      - ./config/core-site.xml:/home/hadoop/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/home/hadoop/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/mapred-site.xml:/home/hadoop/hadoop/etc/hadoop/mapred-site.xml
      - ./config/yarn-site.xml:/home/hadoop/hadoop/etc/hadoop/yarn-site.xml
      - ./config/hadoop-env.sh:/home/hadoop/hadoop/etc/hadoop/hadoop-env.sh
      - ./config/zoo.cfg:/home/hadoop/zookeeper/conf/zoo.cfg
      - master2-journalnode:/home/hadoop/hadoopdata/hdfs/journalnode
      - master2-namenode:/home/hadoop/hadoopdata/hdfs/namenode
      - master2-zookeeper:/home/hadoop/zookeeper/data
    environment:
      - MYID=2
    command: >
      bash -c "
      echo $$MYID > /home/hadoop/zookeeper/data/myid &&
      sudo service ssh start &&
      /home/hadoop/zookeeper/bin/zkServer.sh start &&
      hdfs --daemon start journalnode &&
      sleep 5 &&
      if [ $$MYID -eq 1 ]; then
        hdfs namenode -format mycluster &&
        hdfs --daemon start namenode &&
        hdfs zkfc -formatZK;
      else
        hdfs namenode -bootstrapStandby &&
        hdfs --daemon start namenode &&
        hdfs --daemon start zkfc;
      fi &&
      yarn --daemon start resourcemanager &&
      tail -f /dev/null"

  master3:
    build: .
    hostname: master3
    container_name: master3
    ports:
      - "9873:9870"
      - "8023:8020"
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"
      - "8090:8088"
    volumes:
      - ./config/core-site.xml:/home/hadoop/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/home/hadoop/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/mapred-site.xml:/home/hadoop/hadoop/etc/hadoop/mapred-site.xml
      - ./config/yarn-site.xml:/home/hadoop/hadoop/etc/hadoop/yarn-site.xml
      - ./config/hadoop-env.sh:/home/hadoop/hadoop/etc/hadoop/hadoop-env.sh
      - ./config/zoo.cfg:/home/hadoop/zookeeper/conf/zoo.cfg
      - master3-journalnode:/home/hadoop/hadoopdata/hdfs/journalnode
      - master3-namenode:/home/hadoop/hadoopdata/hdfs/namenode
      - master3-zookeeper:/home/hadoop/zookeeper/data
    environment:
      - MYID=3
    command: >
      bash -c "
      echo $$MYID > /home/hadoop/zookeeper/data/myid &&
      sudo service ssh start &&
      /home/hadoop/zookeeper/bin/zkServer.sh start &&
      hdfs --daemon start journalnode &&
      sleep 5 &&
      if [ $$MYID -eq 1 ]; then
        hdfs namenode -format mycluster &&
        hdfs --daemon start namenode &&
        hdfs zkfc -formatZK;
      else
        hdfs namenode -bootstrapStandby &&
        hdfs --daemon start namenode &&
        hdfs --daemon start zkfc;
      fi &&
      yarn --daemon start resourcemanager &&
      tail -f /dev/null"

  worker1:
    build: .
    hostname: worker1
    container_name: worker1
    volumes:
      - ./config/core-site.xml:/home/hadoop/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/home/hadoop/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/mapred-site.xml:/home/hadoop/hadoop/etc/hadoop/mapred-site.xml
      - ./config/yarn-site.xml:/home/hadoop/hadoop/etc/hadoop/yarn-site.xml
      - ./config/hadoop-env.sh:/home/hadoop/hadoop/etc/hadoop/hadoop-env.sh
      - worker1-datanode:/home/hadoop/hadoopdata/hdfs/datanode
    command: >
      bash -c "
      sudo service ssh start &&
      hdfs --daemon start datanode &&
      yarn --daemon start nodemanager &&
      tail -f /dev/null"

volumes:
  master1-journalnode:
  master1-namenode:
  master1-zookeeper:
  master2-journalnode:
  master2-namenode:
  master2-zookeeper:
  master3-journalnode:
  master3-namenode:
  master3-zookeeper:
  worker1-datanode: